FROM nginx:latest

RUN apt-get update && \
    apt-get install -y certbot python3-certbot-nginx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/ssl.conf /etc/nginx/ssl.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
