services:
  server:
    container_name: prakticum-server
    image: 39_mf_teamwork_01/server:1.0.0-alpha.1
    build:
      context: .
      dockerfile: Dockerfile.server.prod
      args:
        SERVER_PORT: ${SERVER_PORT}
        SERVER_URL: ${SERVER_URL}
        YANDEX_AUTH_URL: ${YANDEX_AUTH_URL}
        YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_URL: ${SERVER_URL}
      YANDEX_AUTH_URL: ${YANDEX_AUTH_URL}
      YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI}
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - prakticum

volumes:
  db-data:
    driver: local
  db-logs:
    driver: local
  pgadmin-data:
    driver: local
networks:
  prakticum:
    name: ${NETWORK}
    driver: ${DRIVER}
