FROM postgres:14-alpine

RUN mkdir -p /var/log/postgresql && \
  chown postgres:postgres /var/log/postgresql

CMD ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql"]
