services:
  server:
    container_name: prakticum-server
    image: 39_mf_teamwork_01/server:1.0.0-alpha.1
    build:
      context: .
      dockerfile: Dockerfile.server.dev
      args:
        SERVER_PORT: ${SERVER_PORT}
        SERVER_URL: ${SERVER_URL}
        YANDEX_AUTH_URL: ${YANDEX_AUTH_URL}
        YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${VITE_PORT}:${VITE_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SERVER_URL: ${SERVER_URL}
      YANDEX_AUTH_URL: ${YANDEX_AUTH_URL}
      YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI}
    volumes:
      - ./packages/client/src:/app/packages/client/src
      - ./packages/server:/app/packages/server
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - prakticum
