ARG NODE_VERSION=18

FROM node:$NODE_VERSION-buster AS base

WORKDIR /app

FROM base AS builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap

FROM node:$NODE_VERSION-buster-slim AS dev
ARG SERVER_PORT
ARG SERVER_URL
ARG YANDEX_AUTH_URL
ARG YANDEX_REDIRECT_URI

WORKDIR /app

COPY --from=builder /app /app

EXPOSE $SERVER_PORT
CMD ["yarn", "dev", "--scope=server"]
