services:
  nginx:
    container_name: prakticum-nginx
    image: ghcr.io/olgazhyzhka/nginx:1.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - certbot-data:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - prakticum

volumes:
  certbot-data:
    driver: local
  certbot-www:
    driver: local

networks:
  prakticum:
    name: ${NETWORK}
    driver: ${DRIVER}
